import{S as q,i as P,a as M}from"./assets/vendor-BkC4bTqC.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))i(t);new MutationObserver(t=>{for(const o of t)if(o.type==="childList")for(const l of o.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&i(l)}).observe(document,{childList:!0,subtree:!0});function s(t){const o={};return t.integrity&&(o.integrity=t.integrity),t.referrerPolicy&&(o.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?o.credentials="include":t.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function i(t){if(t.ep)return;t.ep=!0;const o=s(t);fetch(t.href,o)}})();const y=document.querySelector(".gallery"),f=document.querySelector(".loader"),m=document.querySelector(".showLoad"),$=()=>y.innerHTML="",p=()=>f.classList.add("show"),g=()=>f.classList.remove("show"),L=()=>m.classList.add("show"),u=()=>m.classList.remove("show");function h(r){const e=r.map(({webformatURL:i,largeImageURL:t,tags:o,likes:l,views:b,comments:v,downloads:S})=>`<li class ="gallery-item">
                    <a class = "gallery-link" href="${t}">
                    <img
                        class = "gallery-image"    
                        src = "${i}"
                        alt ="${o}"
                        />
                    </a>
                     <ul class="info">
            <li>Likes<p>${l}</p></li>
            <li>Views<p>${b}</p></li>
            <li>Comments<p>${v}</p></li>
            <li>Downloads<p>${S}</p></li>
            </ul>
                    </li>`).join("");y.insertAdjacentHTML("beforeend",e),new q(".gallery-link",{captionDelay:250,showCounter:!1,captionsData:"alt"}).refresh()}const a=(r,e)=>{P[r]({title:r.charAt(0).toUpperCase()+r.slice(1),message:e,position:"topRight"})};let d=15;const B="https://pixabay.com/api/",x="53507836-a90b7328b368e53f321449aea",w=async(r,e)=>{try{return(await M.get(B,{params:{key:x,q:r,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:d,page:e}})).data}catch{a("error","Problems")}},O=document.querySelector(".form"),A=document.querySelector('[name="search-text"]'),E=document.querySelector(".showLoad");let c="",n=1;O.addEventListener("submit",async r=>{if(r.preventDefault(),c=A.value.trim(),u(),c===""){a("error","Невалидный ввод");return}$(),n=1,p();try{const e=await w(c,n);if(e.hits.length===0)a("error","Sorry, there are no images matching your search query. Please try again!");else{const s=Math.ceil(e.totalHits/d);n>s?a("info","We're sorry, but you've reached the end of search results."):(h(e.hits),L(),s===1&&(u(),a("info","We're sorry, but you've reached the end of search results.")))}}catch{a("error","Sorry, there are no images matching your search query. Please try again!")}finally{g()}});E.addEventListener("click",async()=>{n+=1,u(),p();try{const r=await w(c,n),e=Math.ceil(r.totalHits/d),s=document.querySelector(".gallery-item"),i=s.getBoundingClientRect();n>e||n===e?(u(),a("info","We're sorry, but you've reached the end of search results."),h(r.hits),window.scrollBy({top:i.height*2,behavior:"smooth"})):(h(r.hits),s&&window.scrollBy({top:i.height*2,behavior:"smooth"}),L())}catch{a("error","We're sorry, щось трапилося")}finally{g()}});
//# sourceMappingURL=index.js.map
