import{S as q,i as P,a as M}from"./assets/vendor-BkC4bTqC.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))n(t);new MutationObserver(t=>{for(const o of t)if(o.type==="childList")for(const c of o.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&n(c)}).observe(document,{childList:!0,subtree:!0});function s(t){const o={};return t.integrity&&(o.integrity=t.integrity),t.referrerPolicy&&(o.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?o.credentials="include":t.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function n(t){if(t.ep)return;t.ep=!0;const o=s(t);fetch(t.href,o)}})();const h=document.querySelector(".gallery"),y=document.querySelector(".loader"),f=document.querySelector(".showLoad"),$=()=>h.innerHTML="",m=()=>y.classList.add("show"),p=()=>y.classList.remove("show"),g=()=>f.classList.add("show"),u=()=>f.classList.remove("show");function L(r){const e=r.map(({webformatURL:n,largeImageURL:t,tags:o,likes:c,views:b,comments:S,downloads:v})=>`<li class ="gallery-item">
                    <a class = "gallery-link" href="${t}">
                    <img
                        class = "gallery-image"    
                        src = "${n}"
                        alt ="${o}"
                        />
                    </a>
                     <ul class="info">
            <li>Likes<p>${c}</p></li>
            <li>Views<p>${b}</p></li>
            <li>Comments<p>${S}</p></li>
            <li>Downloads<p>${v}</p></li>
            </ul>
                    </li>`).join("");h.insertAdjacentHTML("beforeend",e),new q(".gallery-link",{captionDelay:250,showCounter:!1,captionsData:"alt"}).refresh()}const a=(r,e)=>{P[r]({title:r.charAt(0).toUpperCase()+r.slice(1),message:e,position:"topRight"})};let d=15;const x="https://pixabay.com/api/",B="53507836-a90b7328b368e53f321449aea",w=async(r,e)=>{try{return(await M.get(x,{params:{key:B,q:r,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:d,page:e}})).data}catch{a("error","Problems")}},O=document.querySelector(".form"),A=document.querySelector('[name="search-text"]'),E=document.querySelector(".showLoad");let l="",i=1;O.addEventListener("submit",async r=>{if(r.preventDefault(),l=A.value.trim(),u(),l===""){a("error","Невалидный ввод");return}$(),i=1,m();try{const e=await w(l,i);if(e.hits.length===0)a("error","Sorry, there are no images matching your search query. Please try again!");else{const s=Math.ceil(e.totalHits/d);i>s?a("info","We're sorry, but you've reached the end of search results."):(L(e.hits),g(),s===1&&(u(),a("info","We're sorry, but you've reached the end of search results.")))}}catch{a("error","Sorry, there are no images matching your search query. Please try again!")}finally{p()}});E.addEventListener("click",async()=>{i+=1,u(),m();try{const r=await w(l,i),e=Math.ceil(r.totalHits/d);if(i>e||i===e)u(),a("info","We're sorry, but you've reached the end of search results.");else{L(r.hits);const s=document.querySelector(".gallery-item");if(s){const n=s.getBoundingClientRect();window.scrollBy({top:n.height*2,behavior:"smooth"})}g()}}catch{a("error","We're sorry, щось трапилося")}finally{p()}});
//# sourceMappingURL=index.js.map
